/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */


/**
 * @class
 * Initializes a new instance of the Foo class.
 * @constructor
 * Foo
 * @member {string} [fooId] The foo id
 * 
 */
export interface Foo {
    fooId?: string;
}
