/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

import { ServiceClientOptions, RequestOptions, ServiceCallback } from 'ms-rest';
import * as models from '../models';


/**
 * @class
 * Widget
 * __NOTE__: An instance of this class is automatically created for an
 * instance of the FooClient.
 */
export interface Widget {

    /**
     * @summary Gets foo
     *
     * @param {object} [options] Optional Parameters.
     * 
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     * 
     * @param {ServiceCallback} [callback] callback function; see ServiceCallback
     * doc in ms-rest index.d.ts for details
     */
    getWidgets(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.Foo>): void;
    getWidgets(callback: ServiceCallback<models.Foo>): void;
}
